---
- name: "Install package {{ apache_package_name }}"
  ansible.builtin.package:
    name:
      - "{{ apache_package_name }}"
      - iptables

- name: "Enable service {{ apache_package_name }}"
  ansible.builtin.systemd:
    name: "{{ apache_package_name }}"
    enabled: true
  when: apache_service_enabled

- name: "Config apache index files"
  ansible.builtin.template:
    src: "index.html.j2"
    dest: "{{ apache_var_www_data }}/index.html"
    mode: "0644"
  notify: Restart apache

- name: "Allow connections on port 80"
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
    jump: ACCEPT
