---
- name: "Install package {{ _apache_package_name }}"
  ansible.builtin.package:
    name:
      - "{{ _apache_package_name }}"
      - iptables
    state: present

- name: "Enable service {{ _apache_package_name }}"
  ansible.builtin.systemd:
    name: "{{ _apache_package_name }}"
    enabled: true
  when: apache_service_enabled

- name: "Config apache index files"
  ansible.builtin.template:
    src: "index.html.j2"
    dest: "{{ apache_web_data }}/index.html"
    mode: "0644"
  notify: Restart apache

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Allow connections on port {{ apache_port }}"
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: "{{ apache_port }}"
    jump: ACCEPT
    action: insert
    state: present
  register: _apache_iptables
  changed_when: _apache_iptables.failed
