---
- name: "Health check"
  ansible.builtin.uri:
    url: http://localhost
    return_content: true
  register: _apache_service_status
  failed_when: false

- name: "Tell service is running"
  ansible.builtin.debug:
    msg: |
      The service is running !!
  when: _apache_service_status.status is defined and _apache_service_status.status == 200

- name: "Tell service is running"
  ansible.builtin.fail:
    msg: |
      The service is not running !!
  when: _apache_service_status.status is defined and _apache_service_status.status != 200
