---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: "Configure apache"
  ansible.builtin.include_tasks: "apache.yml"

- name: "Health check of apache"
  ansible.builtin.include_tasks: "healthcheck.yml"

- name: "Configure ntp server"
  ansible.builtin.include_tasks: "ntp.yml"
  when: ansible_os_family == 'Debian'

- name: "Create apache users"
  ansible.builtin.include_tasks: "users.yml"
