---
- name: "Restart apache"
  ansible.builtin.systemd:
    name: "{{ _apache_package_name }}"
    state: restarted

- name: "Restart ntp"
  ansible.builtin.systemd:
    name: "ntp"
    state: restarted

- name: "Send failed message"
  ansible.builtin.fail:
    msg: "Service is not running"
