---
- name: "Restart apache"
  ansible.builtin.systemd:
    name: "{{ apache_package_name }}"
    state: restarted

- name: "Restart ntp"
  ansible.builtin.systemd:
    name: "ntp"
    state: restarted
